# Generated by Django 3.2 on 2021-05-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invarianterC.section')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invarianterC.directory')),
            ],
            bases=('invarianterC.section',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invarianterC.section')),
                ('text_file', models.FileField(upload_to='uploads/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invarianterC.directory')),
            ],
            bases=('invarianterC.section',),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invarianterC.section')),
                ('sectionCategory', models.CharField(choices=[('1', 'Procedure'), ('2', 'Property'), ('3', 'Lemma'), ('4', 'Assertion'), ('5', 'Invariant'), ('6', 'Precondition'), ('7', 'Postcondition')], max_length=30)),
                ('sectionStatus', models.CharField(choices=[('1', 'Proved'), ('2', 'Invalid'), ('3', 'Counterexample'), ('4', 'Unchecked')], max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invarianterC.file')),
                ('parentSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invarianterC.subsection')),
            ],
            bases=('invarianterC.section',),
        ),
    ]
