# Generated by Django 3.2 on 2021-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invarianterC', '0003_auto_20210517_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text_file',
            field=models.FileField(null=True, upload_to='invarianterC/uploads/'),
        ),
    ]
